nelmio_cors:
    defaults:
        allow_origin: [ 'http://localhost:3000' ]
        allow_methods: [ 'GET', 'POST', 'OPTIONS', 'PUT' ] # Ajoutez les méthodes HTTP nécessaires
        allow_headers: [ 'Content-Type', 'Authorization' ] # Ajoutez les en-têtes nécessaires
        max_age: 3600